language: node_js
node_js:
  - 5.8.0
branches:
  except:
  - gh-pages
script:
  - npm run lint
  - npm run build
before_install:
  - openssl aes-256-cbc -K $encrypted_3849d7fcafbf_key -iv $encrypted_3849d7fcafbf_iv
    -in id_rsa.enc -out id_rsa -d
after_success:
  - npm run gh-pages-travis
env:
  global:
    - SSH_KEY="id_rsa"
    - GIT_NAME="Matt Holland"
    - GIT_EMAIL="hollandmatt@gmail.com"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="master"
